[package]
name = "pygma_render"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
pygma_parser = { path = "../pygma_parser" }
