[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Pygmalion Developers and Contributors"]
description = "Pygmalion - A modular Rust project"
license = "MIT"

[workspace.dependencies]
